application:
  storage-path: /home/fileshares-archiver/archived-files/
  queues:
    deleted-files: files-deleted-archiver-queue
    files-for-archivation: social-low-archiver-queue,social-medium-archiver-queue,social-low-archiver-queue

spring:
  datasource:
    url: jdbc:postgresql://fileshares-archiver-db:5432/fileshares_archiver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq

opentracing:
  jaeger:
    service-name: fileshares-archiver