application:
  queues:
    deleted-files: files-deleted-social-queue
    storage-path: /home/fileshares-archiver/archived-files

spring:
  datasource:
    url: jdbc:postgresql://fileshares-archiver-db:5432/fileshares_archiver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq:5672